---
name: Test consistency

on:
  push:
    branches:
      - main
    paths:
      - '**.ttl'
      - '.github/workflows/test.yml'
  pull_request:
    branches:
      - main
    paths:
      - '**.ttl'
      - '.github/workflows/test.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    container: obolibrary/odklite
    strategy:
      matrix:
        ontology: [ 'gfo-core.ttl', 'gfo-light.ttl' ]
    steps:
      - uses: actions/checkout@v4
      - run: check-rdfxml ${{ matrix.ontology }}
      - run: robot report --profile qc_report/profile.txt -i ${{ matrix.ontology }}
